<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12932" started-at="2022-05-06T07:59:27Z" finished-at="2022-05-06T07:59:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12932" started-at="2022-05-06T07:59:27Z" finished-at="2022-05-06T07:59:40Z">
      <class name="com.platformX.tests.PX_009_Verifikacija_Sekcije_Pravni_Odnosi_Test">
        <test-method status="FAIL" signature="px_009_verifikacija_sekcije_pravni_odnosi_test()[pri:0, instance:com.platformX.tests.PX_009_Verifikacija_Sekcije_Pravni_Odnosi_Test@794cb805]" name="px_009_verifikacija_sekcije_pravni_odnosi_test" duration-ms="12269" started-at="2022-05-06T09:59:27Z" description="test prolazi kroz sve stranice iz sekcija PRAVNI ODNOSI i IZVJESTAJI i verifikuje ih" finished-at="2022-05-06T09:59:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Opomene: Broj kolona nije dobar!  expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Opomene: Broj kolona nije dobar!  expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.platformX.page.Opomene.verifikujOpomene(Opomene.java:42)
	at com.platformX.tests.PX_009_Verifikacija_Sekcije_Pravni_Odnosi_Test.px_009_verifikacija_sekcije_pravni_odnosi_test(PX_009_Verifikacija_Sekcije_Pravni_Odnosi_Test.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- px_009_verifikacija_sekcije_pravni_odnosi_test -->
        <test-method status="PASS" signature="terminateBrowser()[pri:0, instance:com.platformX.tests.PX_009_Verifikacija_Sekcije_Pravni_Odnosi_Test@794cb805]" name="terminateBrowser" is-config="true" duration-ms="643" started-at="2022-05-06T09:59:39Z" finished-at="2022-05-06T09:59:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
      </class> <!-- com.platformX.tests.PX_009_Verifikacija_Sekcije_Pravni_Odnosi_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
