<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="LAPTOP-D8GBQRP8" name="com.platformX.api.tests.PXD_003_Administration_Message_Test" tests="8" failures="1" timestamp="07 jan 2024 19:56:54 GMT" time="52.043" errors="0">
  <testcase name="pxd_003_01_get_administration_message_test2" time="5.906" classname="com.platformX.api.tests.PXD_003_Administration_Message_Test"/>
  <testcase name="pxd_003_03_create_administration_message_test1" time="6.295" classname="com.platformX.api.tests.PXD_003_Administration_Message_Test">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at com.platformX.api.tests.PXD_003_Administration_Message_Test.pxd_003_03_create_administration_message_test1(PXD_003_Administration_Message_Test.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pxd_003_03_create_administration_message_test1 -->
  <testcase name="pxd_003_01_get_administration_message_test1" time="20.629" classname="com.platformX.api.tests.PXD_003_Administration_Message_Test"/>
  <testcase name="pxd_003_02_post_administration_messages_list_test1" time="6.861" classname="com.platformX.api.tests.PXD_003_Administration_Message_Test"/>
  <testcase name="pxd_003_05_delete_administration_message_test1" time="0.000" classname="com.platformX.api.tests.PXD_003_Administration_Message_Test">
    <skipped/>
  </testcase> <!-- pxd_003_05_delete_administration_message_test1 -->
  <testcase name="pxd_003_01_get_administration_message_test4" time="6.307" classname="com.platformX.api.tests.PXD_003_Administration_Message_Test"/>
  <testcase name="pxd_003_01_get_administration_message_test3" time="6.045" classname="com.platformX.api.tests.PXD_003_Administration_Message_Test"/>
  <testcase name="pxd_003_04_update_administration_message_test1" time="0.000" classname="com.platformX.api.tests.PXD_003_Administration_Message_Test">
    <skipped/>
  </testcase> <!-- pxd_003_04_update_administration_message_test1 -->
</testsuite> <!-- com.platformX.api.tests.PXD_003_Administration_Message_Test -->
